### ISSUE TITLE
Discord Link Does Not Work

### ISSUE THREAD

**Issue by Vilagamer999** [chromebot-websites/chromebot.cf#81]
the discord link doesnt work... make sure it is set to unlimited days and uses...
please fix it.

**Comment by Minion3665** [comment]
@Vilagamer999, this is a known issue and will be fixed soon. There was a recent raid on the server and all instant invites got deleted. Sorry for any inconvenience this has caused.

**Comment by Minion3665** [comment]
Locked

**Comment by Minion3665** [comment]
@Vilagamer999 Fixed in pull request #82
